name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Generating list of functions to still be documented
      run: |
        pylint --output-format=json:tmp.json --disable=all --enable=C0116 --fail-under 1 $(git ls-files '*.py')
        echo "# Functions Missing Documentation:" > missing_functions.md
        jq -r '" - \(.[].obj)"' tmp.json >> missing_functions.md
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit and push missing_functions.md
      run: |
        git add missing_functions.md
        git commit -m "GH-Action: Update missing functions report"
        git push
      env:
        # Ensure GitHub token is available to authenticate the push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}